---
- name: Set host name
  sudo: yes
  hostname: name={{ inventory_hostname }}
  when: inventory_hostname not in ["localhost", "127.0.0.1"]

- name: Set /etc/hosts
  sudo: yes
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=0644 backup=yes
  when: not skip_hosts

- name: Set apt proxy if necessary
  sudo: yes
  template:
    src: apt.conf
    dest: /etc/apt/apt.conf.d/00proxy
  when: deb_proxy is defined

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install packages
  apt: pkg={{ item }} state=installed
  with_items:
    - colordiff
    - curl
    - emacs24-nox
    - git
    - git-review
    - lv
    - magit
    - pbzip2
    - python-dev
    - python-pip
    - screen
    - sl
    - vim
    - yaml-mode
  sudo: yes

- name: gather remote user name
  command: whoami
  register: username
  when: sudo_nopass|default()
  changed_when: no
- name: set fact username
  set_fact: username={{username.stdout}}
  when: sudo_nopass|default()
- name: set no password sudoers for ubuntu
  template:
    src: sudoers_nopasswd
    dest: /etc/sudoers.d/dev_nopasswd
  when: sudo_nopass|default()
  sudo: yes
