---
- name: Set host name
  sudo: yes
  hostname: name={{ host }}
  when: host not in ["local", "127.0.0.1"]

- name: Set /etc/hosts
  sudo: yes
  copy: src=hosts dest=/etc/hosts owner=root group=root mode=0644 backup=yes

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: Install packages
  apt: pkg={{ item }} state=installed
  with_items:
    - colordiff
    - curl
    - emacs
    - git
    - git-review
    - lv
    - magit
    - pbzip2
    - screen
    - sl
  sudo: yes
