---
- name: git clone devstack
  git: repo=http://git.openstack.org/openstack-dev/devstack.git
       dest={{ devstack_dir }}
       force=no

- name: Ensure {{ home }}/.bash_completion.d
  file: dest={{ bash_completion_dir }}
        mode=755
        state=directory

- name: Prepare OpenStack CLI bash completions
  file: src=/opt/stack/python-{{ item }}client/tools/{{ item }}.bash_completion
        dest={{ bash_completion_dir }}/{{ item }}
        state=link
        force=yes
  with_items:
    - cinder
    - nova
    - neutron
    - keystone

- name: git clone devstack-tools
  git: repo=https://github.com/amotoki/devstack-tools.git
       dest={{ devstack_tools_dir }}
       force=no

- name: Deploy local.conf
  command: cp {{ item.src }} {{ item.dest }} creates={{ item.dest }}
  with_items:
    - src: "{{ devstack_tools_dir }}/config/local.conf"
      dest: "{{ devstack_dir }}/local.conf"
    - src: "{{ devstack_tools_dir }}/config/local.sh"
      dest: "{{ devstack_dir }}/local.sh"
    - src: "{{ devstack_tools_dir }}/config/01-proxy"
      dest: "{{ devstack_dir }}/01-proxy"
    - src: "{{ devstack_tools_dir }}/config/02-repos"
      dest: "{{ devstack_dir }}/02-repos"
    - src: "{{ devstack_tools_dir }}/config/10-local"
      dest: "{{ devstack_dir }}/10-local"
