- include_vars: "{{item}}"
  with_first_found:
  - "../../../secrets.yml"
  - "../vars/sample_passwords.yml"
  no_log: yes 

- name: set password variable if non-default
  set_fact: "{{item.key}}={{item.value}}"
  when: item.value != "change_me"
  with_dict:
    _admin_password: "{{admin_password}}"
    _mysql_password: "{{mysql_password}}"
    _rabbit_password: "{{rabbit_password}}"
    _service_password: "{{service_password}}"
    _service_token: "{{service_token}}"
    _swift_hash: "{{swift_hash}}"
  no_log: yes
