---
- include_vars: vault.yml
  tags: sensible

- name: Copy dot files
  copy: src=dotfiles/ dest={{ home }} backup=yes

- name: Ensure {{ home }}/.bash_completion.d
  file: dest={{ home }}/.bash_completion.d
        mode=755
        state=directory

- name: Setup SSH configs
  copy: src=ssh/ dest={{ home }}/.ssh
        force=no

- name: Deploy Transifex RC
  template: src=transifexrc.j2 dest={{ home }}/.transifexrc mode=600
  tags: sensible

- name: Setup SSH private key
  template: src=ssh_private_key.j2 dest={{ home }}/.ssh/id_dsa force=no mode=400
  tags: sensible

- name: Copy useful scripts
  copy: src=bin/ dest={{ home }}/bin backup=yes

- name: Install Emacs Lisp files
  copy: src={{ item.src }} dest={{ item.dest }}
        backup=yes
  with_items:
    - src: elisp
      dest: "{{ home }}"
    - src: elisp-auto-install/
      dest: "{{ home }}/.emacs.d/auto-install"

- git: repo=https://github.com/icefox/git-hooks.git
       dest="{{ home }}/git-hooks"

- file: src="{{ home }}/git-hooks/git-hooks"
        dest="{{ home }}/bin/git-hooks"
        state=link
