---
- name: Copy dot files
  copy: src=dotfiles/ dest={{ home }} backup=yes

- name: Ensure {{ home }}/.bash_completion.d
  file: dest={{ home }}/.bash_completion.d
        mode=755
        state=directory

- name: Setup SSH configs
  copy: src=ssh/ dest={{ home }}/.ssh
        force=no

#- name: Setup SSH private key
#  template: src=ssh_private_key.j2 dest={{ home }}/.ssh/id_dsa.ansible force=no mode=400

- name: Copy useful scripts
  copy: src=bin/ dest={{ home }}/bin backup=yes

- name: Install Emacs Lisp files
  copy: src={{ item.src }} dest={{ item.dest }}
        backup=yes
  with_items:
    - src: elisp
      dest: "{{ home }}"
    - src: elisp-auto-install/
      dest: "{{ home }}/.emacs.d/auto-install"
