---
- name: Include site-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../../../secrets.yml"
    - "../vars/secrets_dummy.yml"

- name: Copy dot files
  copy: src=dotfiles/{{item}} dest={{home}}/{{item}} backup=yes
  with_items:
    - .bash_completion
    - .bashrc
    - .emacs
    - .exrc
    - .gitconfig
    - .lv
    - .profile
    - .screenrc

- name: Create .ssh directory
  file: path={{home}}/.ssh mode=0700 state=directory

- name: Setup SSH configs
  copy: src=ssh/{{item}} dest={{home}}/.ssh/{{item}} backup=yes force=no
  with_items:
    - authorized_keys
    - config
    - id_dsa.pub

- name: Deploy Transifex RC
  template: src=transifexrc.j2 dest={{ home }}/.transifexrc mode=0600 backup=yes
  when: transifex_username is defined and transifex_password is defined

- name: Setup SSH private key
  template: src=ssh_private_key.j2 dest={{ home }}/.ssh/id_dsa force=no mode=0400 backup=yes
  when: ssh_private_key is defined

- name: Create bin directory
  file: path={{home}}/bin mode=0755 state=directory

- name: Copy useful scripts
  copy: src=bin/{{item}} dest={{home}}/bin/{{item}} backup=yes
  with_items:
    - Emacs
    - git-clone-openstack-repo.sh

- name: Install Emacs Lisp files
  copy: src={{ item.src }} dest={{ item.dest }}
        backup=yes
  with_items:
    - src: elisp
      dest: "{{ home }}"
    - src: elisp-auto-install/
      dest: "{{ home }}/.emacs.d/auto-install"

- git: repo=https://github.com/icefox/git-hooks.git
       dest="{{ home }}/git-hooks"

- file: src="{{ home }}/git-hooks/git-hooks"
        dest="{{ home }}/bin/git-hooks"
        state=link
