---
- name: git clone devstack
  git: repo=http://git.openstack.org/openstack-dev/devstack.git
       dest={{ devstack_dir }}
       version={{ branch }}
       force=no

- name: Ensure {{ home }}/.bash_completion.d
  file: dest={{ bash_completion_dir }}
        mode=755
        state=directory
  sudo: yes

- name: Prepare OpenStack CLI bash completions
  get_url:
    url: http://git.openstack.org/cgit/openstack/python-{{ item }}client/plain/tools/{{ item }}.bash_completion
    dest: "{{ bash_completion_dir }}/{{ item }}"
    force: yes
  with_items:
    - cinder
    - nova
    - neutron
    - keystone
    - glance
  sudo: yes

- name: git clone devstack-tools
  git: repo=https://github.com/amotoki/devstack-tools.git
       dest={{ devstack_tools_dir }}
       force=no

- name:
  git: repo=https://github.com/amotoki/horizon-i18n-tools.git
       dest={{ horizon_i18n_tools_dir }}
       force=no

- name: Install transifex client
  pip: name=transifex-client
  sudo: yes

- name: Copy local.conf and 99-horizon-i18n
  template: src={{ item.src }} dest={{ item.dest }} backup=yes
  with_items:
  - src: local.conf
    dest: "{{ devstack_dir }}/local.conf"
  - src: 99-horizon-i18n.sh
    dest: "{{ devstack_dir }}/extras.d/99-horizon-i18n.sh"

- name: Install optional packages for OpenStack development
  apt: pkg={{ item }} state=installed
  with_items:
    - libmysqlclient-dev
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - libssl-dev
    - libffi-dev
  sudo: yes

- name: cron import-trans.sh
  cron:
    name: "Horizon import trans"
    minute: 29
    job: "{{ horizon_i18n_tools_dir }}/import-trans.sh -r {{ branch|basename }}"
    user: "{{ ansible_env.USER }}"
    state: absent
